export default function data() {
    const dataSchedule = [
        {
            id: 1,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 1,
        },
        {
            id: 2,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 0,
        },
        {
            id: 3,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 0,
        },
        {
            id: 4,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 1,
        },
        {
            id: 5,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 1,
        },
        {
            id: 6,
            image: require('../src/assets/image/schedule.png'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 0,
        },
    ];

    const Coures = [
        {
            id: 1,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 1,
        },
        {
            id: 2,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 0,
        },
        {
            id: 3,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 2,
        },
        {
            id: 4,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 2,

        },
        {
            id: 5,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 2,

        },
        {
            id: 6,
            image: require('../src/assets/image/abc.jpg'),
            title: 'Bí kíp ứng dụng chat GPT x3 năng suất ',
            content: 'Chương trình đào tạo dành cho đại sứ Futurelang siu cấ vjpro',
            object: 'Đối tượng: Đại sứ & CTV',
            date: 'Thứ 2(06/03)',
            hours: '20:00',
            address: 'TP Hồ Chí Minh',
            status: 0,

        },
    ];
    return {
        Coures, dataSchedule,

    };
}
